### PR TITLE
fix: crash on Android 14 due to changed API

### PR DESCRIPTION
**Pull request by megaacheyounes**
Issue details: https://github.com/HMS-Core/hms-react-native-plugin/issues/333

### CODE REVIEW

**Comment by CMLCNL** [comment]
i implement your pr and i am getting this error. why? can you help? @megaacheyounes 

```
node_modules/@hmscore/react-native-hms-location/android/src/main/java/com/huawei/hms/rn/location/backend/helpers/HMSBroadcastReceiver.java:163: error: cannot find symbol
            context.registerReceiver(getInstance(), getIntentFilter(context), RECEIVER_NOT_EXPORTED);
                                                                              ^
  symbol:   variable RECEIVER_NOT_EXPORTED
  location: class HMSBroadcastReceiver
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
```

**Comment by megaacheyounes** [comment]
Try importing that constant by adding this line to the top of .java file:
```java
import android.content.Context.RECEIVER_NOT_EXPORTED
```

**Review by Findrown — APPROVED** [review]

**Comment by GabrielLim-FastCo** [comment]
Hi, is there any update regarding this error?

**Comment by GabrielLim-FastCo** [comment]
@megaacheyounes is this closed because the fix is released?

**Pull request closed without merging**
