### PR TITLE
fix(Android): replace maven with maven-publish for RN +0.67

### PR DESCRIPTION
**Pull request by keremoge**
fixing problem: `Plugin with id 'maven' not found.`
related issue: #179

### CODE REVIEW

**Comment by iabadie-dataart** [comment]
Hi @keremoge, Do you know when this change will be published? I need it to upgrade my RN project 🤞

**Comment by keremoge** [comment]
> Hi @keremoge, Do you know when this change will be published? I need it to upgrade my RN project 🤞

Hi @iabadie-dataart, unfortunately I don't know whether this PR will be accepted or not. For now I use **patch-package**;
https://github.com/HMS-Core/hms-react-native-plugin/issues/179#issuecomment-1123622593

**Comment by eTryp** [comment]
Hi, any update on this PR ? this should me merged, thanks.

**Comment by iabadie-dataart** [comment]
Hey @ozkulbeng, sorry for the tag. There is some plan in a near future to apply this changes or something like that?
Just to know if i should apply the patch-package or I can wait a little bit more for that.

**Comment by ozkulbeng** [comment]
Hello @iabadie-dataart , @keremoge ,
We are aware of this issue and planning to solve it in our new releases. But there are different development processes in our team so at this time we can't merge your PR directly, thank you for your contribution.

**Pull request closed without merging**
